version: '3'
services:
  app:
    container_name: backend12
    build: ./
    ports:
      - 5000:5000
    links:
      - mongo
    depends_on:
      - mongo
  
  
  mongo:
    container_name: db123
    image: mongo
    ports:
      - 27014:27017